// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
        
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
    static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBejcjn8xef-Z5sfX7jx7BGOOFB7BYgg0',
    appId: '1:853608235837:web:6b4231b8ac8ca357187b54',
    messagingSenderId: '853608235837',
    projectId: 'appunah-58c1a',
    storageBucket: 'appunah-58c1a.firebasestorage.app',
    authDomain: 'appunah-58c1a.firebaseapp.com',
  );

   static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBejcjn8xef-Z5sfX7jx7BGOOFB7BYgg0',
    appId: '1:853608235837:web:6b4231b8ac8ca357187b54',
    messagingSenderId: '853608235837',
    projectId: 'appunah-58c1a',
    storageBucket: 'appunah-58c1a.firebasestorage.app',
    authDomain: 'appunah-58c1a.firebaseapp.com',
  );
    static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBejcjn8xef-Z5sfX7jx7BGOOFB7BYgg0',
    appId: '1:853608235837:web:6b4231b8ac8ca357187b54',
    messagingSenderId: '853608235837',
    projectId: 'appunah-58c1a',
    storageBucket: 'appunah-58c1a.firebasestorage.app',
    authDomain: 'appunah-58c1a.firebaseapp.com',
  );

}